apiVersion: ai.sap.com/v1alpha1
kind: Workflow
metadata:
  name: hello-pipeline
spec:
  entrypoint: main
  templates:
    - name: main
      image: alpine:latest
      command: ["sh", "-c"]
      args: ["echo 'Hello from SAP AI Core!'"]
